/**:
  ros__parameters:
    min_longitudinal_offset: 1.98
    max_longitudinal_offset: 2.10
    min_lateral_offset: -0.8
    max_lateral_offset: 1.09
    min_height_offset: 1.049
    max_height_offset: 1.27
