/**:
  ros__parameters:
    wheel_radius: 0.33 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.20 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 2.72 # between front wheel center and rear wheel center
    wheel_tread: 1.567 # between left wheel center and right wheel center
    front_overhang: 0.96 # between front wheel center and vehicle front
    rear_overhang: 1.0 # between rear wheel center and vehicle rear
    left_overhang: 0.37 # between left wheel center and vehicle left
    right_overhang: 0.37 # between right wheel center and vehicle right
    vehicle_height: 1.620
    max_steer_angle: 0.611 # [rad]
